---
# tasks file for nginx-letsencrypt
- name: "nginx-letsencrypt | download certbot"
  get_url:
    url:  https://dl.eff.org/certbot-auto
    dest: "{{ nginx_letsencrypt_path }}/certbot-auto"
    mode: 0770

- name: "nginx-letsencrypt | run certbot for nginx"
  shell: "{{ nginx_letsencrypt_path }}/certbot-auto" -n --nginx --debug --redirect --agree-tos --email "{{ nginx_letsencrypt_email }}" --domains "{{ nginx_letsencrypt_domain }}"

- name: "nginx-letsencrypt | create cron job"
  cron:
    name: "renew cert"
    minute: "0"
    hour: "0,12"
    job: "python -c 'import random; import time; time.sleep(random.random() * 3600)' && {{ nginx_letsencrypt_path }}/certbot-auto renew"
